
name: '[builder] CI for releases'

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
                GITHUB_USERNAME: ${{ github.actor }}
            run: |
                echo "${GITHUB_TOKEN}" | docker login ghcr.io --username ${GITHUB_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag ghcr.io/gimse/my-quote-db/my-quote-db:1.0.0
